name: quickfIXd
favicon: null
layout_spectrum: 0.00965
typography_spectrum: 0.6712900102138519
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#191611'
    - '#f54d4c'
    - '#029de0'
    - '#c1a68b'
  brandStrength: 0.5088007627055049
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
