name: quickfIXd
favicon: null
layout_spectrum: 0.756949384463951
typography_spectrum: 0.6712900102138519
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5088007627055049
  lightness: 0.289713071892038
  saturation: 0.8915292723104358
  rhythmicContrast: 0.9220071360468864
purpose: []
